### ISSUE TITLE
Make DeveloperError final

### ISSUE THREAD

**Issue by ataulm** [novoda/notils#51]
DeveloperError is a fail-fast mechanism which should be useful during development, similar to asserts.

There's no need to extend DeveloperError - they should never be caught and handled (just fix what you dun goofed on), so they don't need specific types to indicate different types of error.

An example of where you might use a DeveloperError is in the default case of a switch statement where you're handling different loaders in the same activity - a case for each loader ID, and the default case throws DeveloperError("unknown loader id - did you forget to handle a loader that you initialised?").

**Comment by blundell** [comment]
would someone want to extend it with `LegacyDeveloperError` and `ApiTeamDeveloperError` or whatever? What I mean is, what is the benefit of locking it down, how do we know how someone else will use our api?

**Comment by ataulm** [comment]
For me, I would have said that developer errors should be for highlighting
a developer error (our error). I cannot think of a reason why you would
want the class extensible - a typed error suggests it's something more than
merely a developer error.

That said, I don't mind not making this final. But I will :x: anyone I see
extending this :)

On Wed, 27 Apr 2016, 11:57 Paul Blundell, <notifications@github.com> wrote:

> would someone want to extend it with LegacyDeveloperError and
> ApiTeamDeveloperError or whatever? What I mean is, what is the benefit of
> locking it down, how do we know how someone else will use our api?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/novoda/notils/issues/51#issuecomment-215049108>
>

-- 
Disclaimer: The information in this e-mail and any attachments is the 
property of Novoda Ltd and is confidential and may be legally privileged. 
This e-mail is intended solely for the person or organisation to which it 
is addressed. Any disclosure, copying or other use of the information by 
any person or organisation who is not the intended recipient is strictly 
prohibited and may be unlawful. If you have received this e-mail in error, 
please inform the sender immediately and delete/destroy this e-mail and any 
copies of it. Novoda Ltd has taken reasonable precautions to minimise the 
risk of any software viruses which may damage your systems, but we advise 
that you take the necessary steps to ensure that no virus contamination is 
suffered. Novoda Ltd does not accept any liability for any loss or damage 
caused by the transmission of any virus.

Novoda Ltd, Company No: 347444, Registered in Scotland Registered 
Office: C/O Alexander Sloan, 38 Cadogan Street, Glasgow, G2 7HF, Scotland.  VAT 
Registration Number  GB 984 2525 93
