### ISSUE TITLE
Improve AndroidUtils.requestHideKeyboard()

### ISSUE THREAD

**Issue by mr-archano** [novoda/notils#59]
Below a comment from @rock3r:

> ... what I was seeing is that if you don't requestFocus() on the target view the hideSoftInputFromWindow() call doesn't work reliably.

Investigate the correct behaviour of this.

**Comment by rock3r** [comment]
It can also be noted that you don't need to pass a `Context` to that method -- `v.getContext()` will do the trick just fine. Another small note is that you might want to check for `v.isInEditMode()`, or you might break the layout preview/editor if you use it in a custom view.
